package xml.booking.comments.managers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import xml.booking.comments.model.Accommodation;
import xml.booking.comments.repositories.AccommodationRepository;

/**
* Generated by Spring Data Generator on 16/06/2019
*/
@Component
public class AccommodationManager {

	private AccommodationRepository accommodationRepository;

	@Autowired
	public AccommodationManager(AccommodationRepository accommodationRepository) {
		this.accommodationRepository = accommodationRepository;
	}

}
