package xml.booking.comments.managers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import xml.booking.comments.model.Comment;
import xml.booking.comments.repositories.CommentRepository;

/**
* Generated by Spring Data Generator on 16/06/2019
*/
@Component
public class CommentManager {

	private CommentRepository commentRepository;

	@Autowired
	public CommentManager(CommentRepository commentRepository) {
		this.commentRepository = commentRepository;
	}

}
