package xml.booking.comments.managers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import xml.booking.comments.model.Role;
import xml.booking.comments.repositories.RoleRepository;

/**
* Generated by Spring Data Generator on 16/06/2019
*/
@Component
public class RoleManager {

	private RoleRepository roleRepository;

	@Autowired
	public RoleManager(RoleRepository roleRepository) {
		this.roleRepository = roleRepository;
	}

}
