package xml.booking.repositories;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import xml.booking.model.User;

/**
* Generated by Spring Data Generator on 18/05/2019
*/
@Repository
public interface UserRepository extends JpaRepository<User, Long>, JpaSpecificationExecutor<User> {
	
	Page<User> findByUserTypeAndDeleted(String userType, Boolean deleted, Pageable pageable);
	
	User findByIdAndDeleted(Long id, Boolean deleted);
	
	User findByEmailAndDeleted(String email, Boolean deleted);

}
