version: '3'
services:
  service-registry:
    image: ftntim1/xml-booking:service-registry
    build: 
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - megatravel-network

  api-gateway:
    image: ftntim1/xml-booking:api-gateway
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network

  authentication-service:
    image: ftntim1/xml-booking:authentication-service
    build: 
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "9994:9994"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network

  authentication-soap-service:
    image: ftntim1/xml-booking:authentication-soap-service
    build: 
      context: ./authentication-soap-service
      dockerfile: Dockerfile
    ports:
      - "9992:9992"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network

  accommodation-soap-service:
    image: ftntim1/xml-booking:accommodation-soap-service
    build: 
      context: ./accommodation-soap-service
      dockerfile: Dockerfile
    ports:
      - "9998:9998"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network

  reservation-soap-service:
    image: ftntim1/xml-booking:reservation-soap-service
    build: 
      context: ./reservation-soap-service
      dockerfile: Dockerfile
    ports:
      - "9993:9993"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network

  messaging-soap-service:
    image: ftntim1/xml-booking:messaging-soap-service
    build: 
      context: ./messaging-soap-service
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network

  comments-service:
    image: ftntim1/xml-booking:comments-service
    build: 
      context: ./comments-service
      dockerfile: Dockerfile
    ports:
      - "9991:9991"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network

  search-service:
    image: ftntim1/xml-booking:search-service
    ports:
      - "8095:8095"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network

  user-managing-service:
    image: ftntim1/xml-booking:user-managing-service
    ports:
      - "8096:8096"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network

  accommodation-service:
    image: ftntim1/xml-booking:accommodation-service
    build: 
      context: ./accommodation-service
      dockerfile: Dockerfile
    ports:
      - "9970:9970"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network

  client-message:
    image: ftntim1/xml-booking:client-message
    ports:
      - "9978:9978"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network
  
  maintenance-of-the-code-book:
    image: ftntim1/xml-booking:maintenance-of-the-code-book
    ports:
      - "9979:9979"
    links:
      - service-registry
    depends_on:   
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network

  reservations:
    image: ftntim1/xml-booking:reservations
    build: 
      context: ./reservations
      dockerfile: Dockerfile
    ports:
      - "9977:9977"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - megatravel-network


networks:
  megatravel-network:
    driver: bridge