package xml.booking.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import xml.booking.model.AccommodationCategory;

/**
* Generated by Spring Data Generator on 18/05/2019
*/
@Repository
public interface AccommodationCategoryRepository extends JpaRepository<AccommodationCategory, Long>, JpaSpecificationExecutor<AccommodationCategory> {

	@Query("select acat from Accommodation as acc inner join acc.accommodationUnit as au "
			 + "inner join acc.accommodationCategory as acat where au.id = ?1")
		AccommodationCategory findCategoryByAccommodationUnitId(Long accommodationUnitId);
}
