//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.18 at 12:12:13 AM CEST 
//


package rs.ac.uns.ftn.tim1.accommodation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="default_price" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="cancelation_period" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/tim1/accommodation}Day" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "name",
    "capacity",
    "defaultPrice",
    "cancelationPeriod",
    "day"
})
@XmlRootElement(name = "AccommodationUnit")
public class AccommodationUnit {

    @XmlElement(required = true)
    protected Object id;
    @XmlElement(required = true)
    protected Object name;
    @XmlElement(required = true)
    protected Object capacity;
    @XmlElement(name = "default_price", required = true)
    protected Object defaultPrice;
    @XmlElement(name = "cancelation_period", required = true)
    protected Object cancelationPeriod;
    @XmlElement(name = "Day")
    protected List<Day> day;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setId(Object value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setName(Object value) {
        this.name = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCapacity(Object value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the defaultPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDefaultPrice() {
        return defaultPrice;
    }

    /**
     * Sets the value of the defaultPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDefaultPrice(Object value) {
        this.defaultPrice = value;
    }

    /**
     * Gets the value of the cancelationPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCancelationPeriod() {
        return cancelationPeriod;
    }

    /**
     * Sets the value of the cancelationPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCancelationPeriod(Object value) {
        this.cancelationPeriod = value;
    }

    /**
     * Gets the value of the day property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the day property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Day }
     * 
     * 
     */
    public List<Day> getDay() {
        if (day == null) {
            day = new ArrayList<Day>();
        }
        return this.day;
    }

}
