package xml.booking.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import xml.booking.model.AccommodationUnit;
import java.util.Optional;


/**
* Generated by Spring Data Generator on 31/05/2019
*/
@Repository
public interface AccommodationUnitRepository extends JpaRepository<AccommodationUnit, Long>, JpaSpecificationExecutor<AccommodationUnit> {

	Optional<AccommodationUnit> findByIdAndDeleted(long accommodationUnitId, boolean deleted);
}
