package xml.booking.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import xml.booking.model.Accommodation;

/**
* Generated by Spring Data Generator on 31/05/2019
*/
@Repository
public interface AccommodationRepository extends JpaRepository<Accommodation, Long>, JpaSpecificationExecutor<Accommodation> {

	Accommodation getOne(Long id);

	Optional<Accommodation> findByIdAndDeleted(long accommodationId, boolean b);

	List<Accommodation> findByDeletedEquals(boolean b);

	List<Accommodation> findByUserEmailAndDeleted(String email, boolean b);
}
