package xml.booking.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import xml.booking.model.AccommodationCategory;

/**
* Generated by Spring Data Generator on 31/05/2019
*/
@Repository
public interface AccommodationCategoryRepository extends JpaRepository<AccommodationCategory, Long>, JpaSpecificationExecutor<AccommodationCategory> {

	List<AccommodationCategory> findByDeletedEquals(boolean b);

}
