package xml.booking.managers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import xml.booking.model.AdditionalService;
import xml.booking.repositories.AdditionalServiceRepository;

/**
* Generated by Spring Data Generator on 09/06/2019
*/
@Component
public class AdditionalServiceManager {

	private AdditionalServiceRepository additionalServiceRepository;

	@Autowired
	public AdditionalServiceManager(AdditionalServiceRepository additionalServiceRepository) {
		this.additionalServiceRepository = additionalServiceRepository;
	}

}
