//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.29 at 08:07:47 PM CEST 
//


package xml.booking.accommodationsoap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accommodation_unit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accommodationUnitId"
})
@XmlRootElement(name = "deleteAccommodationUnitRequest")
public class DeleteAccommodationUnitRequest {

    @XmlElement(name = "accommodation_unit_id")
    protected long accommodationUnitId;

    /**
     * Gets the value of the accommodationUnitId property.
     * 
     */
    public long getAccommodationUnitId() {
        return accommodationUnitId;
    }

    /**
     * Sets the value of the accommodationUnitId property.
     * 
     */
    public void setAccommodationUnitId(long value) {
        this.accommodationUnitId = value;
    }

}
