//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.29 at 08:07:47 PM CEST 
//


package xml.booking.accommodationsoap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import xml.booking.model.Accommodation;
import xml.booking.model.AccommodationCategory;
import xml.booking.model.AccommodationType;
import xml.booking.model.AccommodationUnit;
import xml.booking.model.AdditionalService;
import xml.booking.model.Day;
import xml.booking.model.Image;
import xml.booking.model.Location;
import xml.booking.model.User;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.tim1.accommodationsoap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAccommodationCategoriesRequest_QNAME = new QName("http://www.ftn.uns.ac.rs/tim1/accommodationsoap", "getAccommodationCategoriesRequest");
    private final static QName _GetAccommodationTypesRequest_QNAME = new QName("http://www.ftn.uns.ac.rs/tim1/accommodationsoap", "getAccommodationTypesRequest");
    private final static QName _GetAdditionalServicesRequest_QNAME = new QName("http://www.ftn.uns.ac.rs/tim1/accommodationsoap", "getAdditionalServicesRequest");
    private final static QName _GetAccommodationsRequest_QNAME = new QName("http://www.ftn.uns.ac.rs/tim1/accommodationsoap", "getAccommodationsRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.tim1.accommodationsoap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link GetAdditionalServicesResponse }
     * 
     */
    public GetAdditionalServicesResponse createGetAdditionalServicesResponse() {
        return new GetAdditionalServicesResponse();
    }

    /**
     * Create an instance of {@link AdditionalService }
     * 
     */
    public AdditionalService createAdditionalService() {
        return new AdditionalService();
    }

    /**
     * Create an instance of {@link Day }
     * 
     */
    public Day createDay() {
        return new Day();
    }

    /**
     * Create an instance of {@link CreateAccommodationUnitResponse }
     * 
     */
    public CreateAccommodationUnitResponse createCreateAccommodationUnitResponse() {
        return new CreateAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitResponse }
     * 
     */
    public GetAccommodationUnitResponse createGetAccommodationUnitsResponse() {
        return new GetAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link AccommodationUnit }
     * 
     */
    public AccommodationUnit createAccommodationUnit() {
        return new AccommodationUnit();
    }

    /**
     * Create an instance of {@link GetAccommodationCategoriesResponse }
     * 
     */
    public GetAccommodationCategoriesResponse createGetAccommodationCategoriesResponse() {
        return new GetAccommodationCategoriesResponse();
    }

    /**
     * Create an instance of {@link AccommodationCategory }
     * 
     */
    public AccommodationCategory createAccommodationCategory() {
        return new AccommodationCategory();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitRequest }
     * 
     */
    public GetAccommodationUnitRequest createGetAccommodationUnitRequest() {
        return new GetAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link UpdateAccommodationUnitResponse }
     * 
     */
    public UpdateAccommodationUnitResponse createUpdateAccommodationUnitResponse() {
        return new UpdateAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link UpdateAccommodationUnitRequest }
     * 
     */
    public UpdateAccommodationUnitRequest createUpdateAccommodationUnitRequest() {
        return new UpdateAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link DeleteAccommodationResponse }
     * 
     */
    public DeleteAccommodationResponse createDeleteAccommodationResponse() {
        return new DeleteAccommodationResponse();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link GetAccommodationsResponse }
     * 
     */
    public GetAccommodationsResponse createGetAccommodationsResponse() {
        return new GetAccommodationsResponse();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link AccommodationType }
     * 
     */
    public AccommodationType createAccommodationType() {
        return new AccommodationType();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link GetAccommodationImagesResponse }
     * 
     */
    public GetAccommodationImagesResponse createGetAccommodationImagesResponse() {
        return new GetAccommodationImagesResponse();
    }

    /**
     * Create an instance of {@link UpdateAccommodationResponse }
     * 
     */
    public UpdateAccommodationResponse createUpdateAccommodationResponse() {
        return new UpdateAccommodationResponse();
    }

    /**
     * Create an instance of {@link CreateAccommodationRequest }
     * 
     */
    public CreateAccommodationRequest createCreateAccommodationRequest() {
        return new CreateAccommodationRequest();
    }

    /**
     * Create an instance of {@link DeleteAccommodationUnitResponse }
     * 
     */
    public DeleteAccommodationUnitResponse createDeleteAccommodationUnitResponse() {
        return new DeleteAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link DeleteAccommodationRequest }
     * 
     */
    public DeleteAccommodationRequest createDeleteAccommodationRequest() {
        return new DeleteAccommodationRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationTypesResponse }
     * 
     */
    public GetAccommodationTypesResponse createGetAccommodationTypesResponse() {
        return new GetAccommodationTypesResponse();
    }

    /**
     * Create an instance of {@link CreateAccommodationResponse }
     * 
     */
    public CreateAccommodationResponse createCreateAccommodationResponse() {
        return new CreateAccommodationResponse();
    }

    /**
     * Create an instance of {@link UpdateAccommodationRequest }
     * 
     */
    public UpdateAccommodationRequest createUpdateAccommodationRequest() {
        return new UpdateAccommodationRequest();
    }

    /**
     * Create an instance of {@link CreateAccommodationUnitRequest }
     * 
     */
    public CreateAccommodationUnitRequest createCreateAccommodationUnitRequest() {
        return new CreateAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link DeleteAccommodationUnitRequest }
     * 
     */
    public DeleteAccommodationUnitRequest createDeleteAccommodationUnitRequest() {
        return new DeleteAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationImagesRequest }
     * 
     */
    public GetAccommodationImagesRequest createGetAccommodationImagesRequest() {
        return new GetAccommodationImagesRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/tim1/accommodationsoap", name = "getAccommodationCategoriesRequest")
    public JAXBElement<Object> createGetAccommodationCategoriesRequest(Object value) {
        return new JAXBElement<Object>(_GetAccommodationCategoriesRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/tim1/accommodationsoap", name = "getAccommodationTypesRequest")
    public JAXBElement<Object> createGetAccommodationTypesRequest(Object value) {
        return new JAXBElement<Object>(_GetAccommodationTypesRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/tim1/accommodationsoap", name = "getAdditionalServicesRequest")
    public JAXBElement<Object> createGetAdditionalServicesRequest(Object value) {
        return new JAXBElement<Object>(_GetAdditionalServicesRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/tim1/accommodationsoap", name = "getAccommodationsRequest")
    public JAXBElement<Object> createGetAccommodationsRequest(Object value) {
        return new JAXBElement<Object>(_GetAccommodationsRequest_QNAME, Object.class, null, value);
    }

}
