package xml.booking.auth.managers;

import xml.booking.auth.model.User;
import xml.booking.auth.repositories.UserRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 09/06/2019
*/
@Component
public class UserManager {

	private UserRepository userRepository;

	@Autowired
	public UserManager(UserRepository userRepository) {
		this.userRepository = userRepository;
	}

}
