package xml.booking.managers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import xml.booking.model.Accommodation;
import xml.booking.repositories.AccommodationRepository;

/**
* Generated by Spring Data Generator on 08/06/2019
*/
@Component
public class AccommodationManager {

	private AccommodationRepository accommodationRepository;

	@Autowired
	public AccommodationManager(AccommodationRepository accommodationRepository) {
		this.accommodationRepository = accommodationRepository;
	}

}
