package xml.booking.managers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import xml.booking.model.AccommodationUnit;
import xml.booking.repositories.AccommodationUnitRepository;

/**
* Generated by Spring Data Generator on 08/06/2019
*/
@Component
public class AccommodationUnitManager {

	private AccommodationUnitRepository accommodationUnitRepository;

	@Autowired
	public AccommodationUnitManager(AccommodationUnitRepository accommodationUnitRepository) {
		this.accommodationUnitRepository = accommodationUnitRepository;
	}

}
