package xml.booking.repositories;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import xml.booking.model.AccommodationUnit;
import xml.booking.model.Day;

/**
* Generated by Spring Data Generator on 19/06/2019
*/
@Repository
public interface AccommodationUnitRepository extends JpaRepository<AccommodationUnit, Long>, JpaSpecificationExecutor<AccommodationUnit> {
	AccommodationUnit findByIdAndDeleted(Long id, boolean deleted);
	Page<AccommodationUnit> findByDeleted(Pageable page, boolean deleted);
	List<AccommodationUnit> findByDeleted(boolean deleted);
	@Query("SELECT days FROM AccommodationUnit AS accU inner join accU.day AS days where accU.id = ?1 AND days.date >= ?2 and days.date <= ?3")
	List<Day> findDaysBetween( Long id, Long from, Long to);
	
	@Query("SELECT au FROM AccommodationUnit as au WHERE au.id = ?1 and au.deleted=false "
			+ "and au not in (select distinct unit from Reservation as res inner join res.accommodationUnit as unit where "
		     + "((res.beginningDate <= ?2 and res.endDate >= ?3) or (res.beginningDate >= ?2 and res.beginningDate < ?3) or " 
		     + "(res.endDate > ?2 and res.endDate <= ?3)) and res.deleted = false and unit.deleted = false)"
		     + "and au not in (select distinct acunit from AccommodationUnit as acunit inner join acunit.day as dd "
		     + "where dd.date >= ?2 and dd.date <= ?3 and dd.available = false and acunit.deleted = false)")
	AccommodationUnit checkIsFreeForReservation( Long id, Long from, Long to);
}
