package xml.booking.managers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import xml.booking.model.JwtToken;
import xml.booking.repositories.JwtTokenRepository;

/**
* Generated by Spring Data Generator on 31/05/2019
*/
@Component
public class JwtTokenManager {

	private JwtTokenRepository jwtTokenRepository;

	@Autowired
	public JwtTokenManager(JwtTokenRepository jwtTokenRepository) {
		this.jwtTokenRepository = jwtTokenRepository;
	}

}
