package xml.booking.managers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import xml.booking.model.Message;
import xml.booking.repositories.MessageRepository;

/**
* Generated by Spring Data Generator on 18/05/2019
*/
@Component
public class MessageManager {

	private MessageRepository messageRepository;

	@Autowired
	public MessageManager(MessageRepository messageRepository) {
		this.messageRepository = messageRepository;
	}

}
