package xml.booking.managers;

import java.util.function.Function;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Component;

import xml.booking.dto.UserDTO;
import xml.booking.model.User;
import xml.booking.repositories.UserRepository;

/**
* Generated by Spring Data Generator on 18/05/2019
*/
@Component
public class UserManager {

	@Autowired
	private UserRepository userRepository;
	
	public Page<UserDTO> findAllUsersByTypeAndDeleted(String userType, Pageable page){
		
		Page<User> users = userRepository.findByUserTypeAndDeleted(userType, false, page);
		
		return mapToDTO(users);
	}
	
	public User findUserByIdAndDeleted(Long id) {
		
		return userRepository.findByIdAndDeleted(id, false);		
	}
	
	public User findUserByEmailAndDeleted(String email) {
		
		return userRepository.findByEmailAndDeleted(email, false);
	}
	
	public User updateUser(User user) {
		
		return userRepository.save(user);
	}
	
	private Page<UserDTO> mapToDTO(Page<User> users){
		
		Page<UserDTO> dtos = users.map(new Function<User, UserDTO>() {
		    @Override
		    public UserDTO apply(User user) {		    	
		    	UserDTO userDTO = new UserDTO(user);

		    	return userDTO;
		    }
		});
		
		return dtos;		
	}

	
}
