package xml.booking.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import xml.booking.model.Reservation;

/**
* Generated by Spring Data Generator on 09/06/2019
*/
@Repository
public interface ReservationRepository extends JpaRepository<Reservation, Long>, JpaSpecificationExecutor<Reservation> {

	List<Reservation> findByUserId(Long id);

	Reservation findByIdAndDeleted(Long reservationId, boolean b);

	List<Reservation> findByUserIdAndDeleted(Long id, boolean b);

}
