package xml.booking.auth.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import xml.booking.auth.model.Role;

/**
* Generated by Spring Data Generator on 09/06/2019
*/
@Repository
public interface RoleRepository extends JpaRepository<Role, Long>, JpaSpecificationExecutor<Role> {

	Role findByRole(String upperCase);

}
