package xml.booking.managers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import xml.booking.model.AccommodationUnit;
import xml.booking.repositories.AccommodationUnitRepository;

/**
* Generated by Spring Data Generator on 18/05/2019
*/
@Component
public class AccommodationUnitManager {

	@Autowired
	private AccommodationUnitRepository accommodationUnitRepository;

	

}
