package xml.booking.comments.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import xml.booking.comments.model.Comment;
import xml.booking.comments.model.Reservation;

/**
* Generated by Spring Data Generator on 16/06/2019
*/
@Repository
public interface ReservationRepository extends JpaRepository<Reservation, Long>, JpaSpecificationExecutor<Reservation> {

	List<Reservation> findByAccommodationUnitId(Long accommodationUnitId);

}
