//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.18 at 12:12:13 AM CEST 
//


package xml.booking.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.hibernate.annotations.ColumnDefault;

import lombok.EqualsAndHashCode;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="beginning_date" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="finalPrice">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="3"/>
 *               &lt;totalDigits value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="checked_in" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/tim1/reservation}Rating" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/tim1/reservation}Message" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/tim1/reservation}Comment" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/tim1/accommodation}AccommodationUnit"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/tim1/user}User" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "beginningDate",
    "endDate",
    "finalPrice",
    "checkedIn",
    "rating",
    "message",
    "comment",
    "accommodationUnit",
    "user"
})
@XmlRootElement(name = "Reservation")
@Entity
@SequenceGenerator(name="seqReserv", initialValue=100, allocationSize=50)
@EqualsAndHashCode
public class Reservation {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seqReserv")
    protected Long id;
	
    @XmlElement(name = "beginning_date", required = true)
    @Column(name = "beginningDate")
    protected Long beginningDate;
    
    @XmlElement(name = "end_date", required = true)
    @Column(name = "endDate")
    protected Long endDate;
    
    @XmlElement(required = true)
    @Column(name = "finalPrice")
    protected BigDecimal finalPrice;
    
    @XmlElement(name = "checked_in", defaultValue = "false")
    @Column(name = "checkedIn")
    protected boolean checkedIn;
    
    @XmlElement(name = "AccommodationUnit", namespace = "http://www.ftn.uns.ac.rs/tim1/accommodationUnit", required = true)
    @ManyToOne
    protected AccommodationUnit accommodationUnit;
    
    @Column(name = "deleted")
    @ColumnDefault(value = "false")
	protected boolean deleted;

    /**
     * Gets the value of the id property.
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the beginningDate property.
     * 
     */
    public long getBeginningDate() {
        return beginningDate;
    }

    /**
     * Sets the value of the beginningDate property.
     * 
     */
    public void setBeginningDate(long value) {
        this.beginningDate = value;
    }


    /**
     * Gets the value of the endDate property.
     * 
     */
    public long getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     */
    public void setEndDate(long value) {
        this.endDate = value;
    }


    /**
     * Gets the value of the finalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFinalPrice() {
        return finalPrice;
    }

    /**
     * Sets the value of the finalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFinalPrice(BigDecimal value) {
        this.finalPrice = value;
    }

    /**
     * Gets the value of the checkedIn property.
     * 
     */
    public boolean isCheckedIn() {
        return checkedIn;
    }

    /**
     * Sets the value of the checkedIn property.
     * 
     */
    public void setCheckedIn(boolean value) {
        this.checkedIn = value;
    }
    
    public AccommodationUnit getAccommodationUnit() {
		return accommodationUnit;
	}

	public void setAccommodationUnit(AccommodationUnit accommodationUnit) {
		this.accommodationUnit = accommodationUnit;
	}

	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public void setBeginningDate(Long beginningDate) {
		this.beginningDate = beginningDate;
	}

	public void setEndDate(Long endDate) {
		this.endDate = endDate;
	}


}
