//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.25 at 02:12:16 PM CEST 
//


package xml.booking.comments.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.hibernate.annotations.ColumnDefault;

import lombok.EqualsAndHashCode;



@Entity
@SequenceGenerator(name="seqAcc", initialValue=100, allocationSize=50)
@EqualsAndHashCode
public class Accommodation {

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seqAcc")
    protected Long id;

 
    
    @Column(name = "deleted")
    @ColumnDefault(value = "false")
	protected boolean deleted;



    @OneToMany
    protected List<AccommodationUnit> accommodationUnit;

    
	public Long getId() {
		return id;
	}



	public void setId(Long id) {
		this.id = id;
	}



	public List<AccommodationUnit> getAccommodationUnit() {
		return accommodationUnit;
	}



	public void setAccommodationUnit(List<AccommodationUnit> accommodationUnit) {
		this.accommodationUnit = accommodationUnit;
	}
 

    
}
