package xml.booking.managers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import xml.booking.model.User;
import xml.booking.repositories.UserRepository;

/**
* Generated by Spring Data Generator on 29/05/2019
*/
@Component
public class UserManager {

	private UserRepository userRepository;

	@Autowired
	public UserManager(UserRepository userRepository) {
		this.userRepository = userRepository;
	}

}
