//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.15 at 12:14:54 PM CEST 
//


package xml.booking.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.hibernate.annotations.ColumnDefault;

import lombok.EqualsAndHashCode;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="beginning_date" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="finalPrice">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="3"/>
 *               &lt;totalDigits value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="checked_in" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/tim1/reservationsoap}Rating" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/tim1/reservationsoap}Message" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/tim1/reservationsoap}Comment" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/tim1/reservationsoap}User" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/tim1/reservationsoap}AccommodationUnit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "beginningDate",
    "endDate",
    "finalPrice",
    "checkedIn",
    "rating",
    "message",
    "comment",
    "user",
    "accommodationUnit"
}, namespace="http://www.ftn.uns.ac.rs/tim1/reservationsoap")
@XmlRootElement(name = "Reservation")
@Entity
@SequenceGenerator(name="seqReserv", initialValue=100, allocationSize=50)
@EqualsAndHashCode
public class Reservation {

	@XmlElement(namespace="http://www.ftn.uns.ac.rs/tim1/reservationsoap")
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seqReserv")
    protected Long id;
	
	
    @XmlElement(name = "beginning_date", required = true, namespace="http://www.ftn.uns.ac.rs/tim1/reservationsoap")
    @Column(name = "beginningDate")
    protected Long beginningDate;
    
    @XmlElement(name = "end_date", required = true, namespace="http://www.ftn.uns.ac.rs/tim1/reservationsoap")
    @Column(name = "endDate")
    protected Long endDate;
    
    @XmlElement(required = true, namespace="http://www.ftn.uns.ac.rs/tim1/reservationsoap")
    @Column(name = "finalPrice")
    protected BigDecimal finalPrice;
    
    @XmlElement(name = "checked_in", defaultValue = "false", namespace="http://www.ftn.uns.ac.rs/tim1/reservationsoap")
    @Column(name = "checkedIn")
    protected Boolean checkedIn;
    
    @XmlElement(name = "Rating", namespace="http://www.ftn.uns.ac.rs/tim1/reservationsoap")
    @ManyToOne
    protected Rating rating;
    
    @XmlElement(name = "Message", namespace="http://www.ftn.uns.ac.rs/tim1/reservationsoap")
    @OneToMany(fetch = FetchType.EAGER)
    protected List<Message> message;
    
    @XmlElement(name = "Comment", namespace="http://www.ftn.uns.ac.rs/tim1/reservationsoap")
    @ManyToOne
    protected Comment comment;
    
    
    @XmlElement(name = "User", namespace="http://www.ftn.uns.ac.rs/tim1/reservationsoap")
    @ManyToOne
    protected User user;
    
    @XmlElement(name = "AccommodationUnit", required = true, namespace="http://www.ftn.uns.ac.rs/tim1/reservationsoap")
    @ManyToOne
    protected AccommodationUnit accommodationUnit;

    @XmlTransient
    @Column(name = "deleted")
    @ColumnDefault(value = "false")
	protected boolean deleted;
    /**
     * Gets the value of the id property.
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the beginningDate property.
     * 
     */
    public Long getBeginningDate() {
        return beginningDate;
    }

    /**
     * Sets the value of the beginningDate property.
     * 
     */
    public void setBeginningDate(Long value) {
        this.beginningDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     */
    public Long getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     */
    public void setEndDate(Long value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the finalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFinalPrice() {
        return finalPrice;
    }

    /**
     * Sets the value of the finalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFinalPrice(BigDecimal value) {
        this.finalPrice = value;
    }

    /**
     * Gets the value of the checkedIn property.
     * 
     */
    public Boolean isCheckedIn() {
        return checkedIn;
    }

    /**
     * Sets the value of the checkedIn property.
     * 
     */
    public void setCheckedIn(Boolean value) {
        this.checkedIn = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link Rating }
     *     
     */
    public Rating getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rating }
     *     
     */
    public void setRating(Rating value) {
        this.rating = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Message }
     * 
     * 
     */
    public List<Message> getMessage() {
        if (message == null) {
            message = new ArrayList<Message>();
        }
        return this.message;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the accommodationUnit property.
     * 
     * @return
     *     possible object is
     *     {@link AccommodationUnit }
     *     
     */
    public AccommodationUnit getAccommodationUnit() {
        return accommodationUnit;
    }

    /**
     * Sets the value of the accommodationUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccommodationUnit }
     *     
     */
    public void setAccommodationUnit(AccommodationUnit value) {
        this.accommodationUnit = value;
    }

}
