# Generated by Django 2.1.5 on 2019-04-21 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name=280)),
                ('timestamp', models.DateTimeField()),
                ('mine', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning', models.DateField()),
                ('end', models.DateField()),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checked_in', models.BooleanField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Guest')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.AccommodationUnit')),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='services',
            field=models.ManyToManyField(to='booking.AdditionalService'),
        ),
        migrations.AddField(
            model_name='message',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Reservation'),
        ),
    ]
