# Generated by Django 2.1.5 on 2019-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='services',
            field=models.ManyToManyField(blank=True, to='booking.AdditionalService'),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('unit', 'date')},
        ),
    ]
