# Generated by Django 2.1.5 on 2019-06-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190529_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationcategory',
            name='value',
        ),
        migrations.AddField(
            model_name='accommodationcategory',
            name='name',
            field=models.CharField(default='AAA', max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
