# Generated by Django 2.1.5 on 2019-06-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_cheat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
