//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 04:36:29 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.ac.rs/tim1/loginsoap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xml.booking.auth.soap;
