package xml.booking.repositories;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import xml.booking.model.AdditionalService;

/**
* Generated by Spring Data Generator on 07/06/2019
*/
@Repository
public interface AdditionalServiceRepository extends JpaRepository<AdditionalService, Long>, JpaSpecificationExecutor<AdditionalService> {
	Page<AdditionalService> findByDeleted(Pageable page,boolean deleted);
	List<AdditionalService> findByDeleted(boolean deleted);
	AdditionalService findByDeletedAndId(boolean deleted, Long id);
}
