//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.09 at 04:23:51 AM CEST 
//


package xml.booking.reservationsoap;

import javax.xml.bind.annotation.XmlRegistry;

import xml.booking.model.Accommodation;
import xml.booking.model.AccommodationCategory;
import xml.booking.model.AccommodationType;
import xml.booking.model.AccommodationUnit;
import xml.booking.model.AdditionalService;
import xml.booking.model.Comment;
import xml.booking.model.Day;
import xml.booking.model.Image;
import xml.booking.model.Location;
import xml.booking.model.Message;
import xml.booking.model.Rating;
import xml.booking.model.Reservation;
import xml.booking.model.User;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.tim1.messagingsoap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.tim1.messagingsoap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link CreateReservationResponse }
     * 
     */
    public CreateReservationResponse createCreateReservationResponse() {
        return new CreateReservationResponse();
    }

    /**
     * Create an instance of {@link CreateReservationRequest }
     * 
     */
    public CreateReservationRequest createCreateReservationRequest() {
        return new CreateReservationRequest();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link AccommodationCategory }
     * 
     */
    public AccommodationCategory createAccommodationCategory() {
        return new AccommodationCategory();
    }

    /**
     * Create an instance of {@link AccommodationType }
     * 
     */
    public AccommodationType createAccommodationType() {
        return new AccommodationType();
    }

    /**
     * Create an instance of {@link AdditionalService }
     * 
     */
    public AdditionalService createAdditionalService() {
        return new AdditionalService();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link AccommodationUnit }
     * 
     */
    public AccommodationUnit createAccommodationUnit() {
        return new AccommodationUnit();
    }

    /**
     * Create an instance of {@link Day }
     * 
     */
    public Day createDay() {
        return new Day();
    }

    /**
     * Create an instance of {@link GetReservationRequest }
     * 
     */
    public GetReservationRequest createGetReservationRequest() {
        return new GetReservationRequest();
    }

    /**
     * Create an instance of {@link GetReservationResponse }
     * 
     */
    public GetReservationResponse createGetReservationResponse() {
        return new GetReservationResponse();
    }

    /**
     * Create an instance of {@link GetReservationMessagesRequest }
     * 
     */
    public GetReservationMessagesRequest createGetReservationMessagesRequest() {
        return new GetReservationMessagesRequest();
    }

    /**
     * Create an instance of {@link DeclineReservationRequest }
     * 
     */
    public DeclineReservationRequest createDeclineReservationRequest() {
        return new DeclineReservationRequest();
    }

    /**
     * Create an instance of {@link GetReservationsListResponse }
     * 
     */
    public GetReservationsListResponse createGetReservationsListResponse() {
        return new GetReservationsListResponse();
    }

    /**
     * Create an instance of {@link GetReservationsListRequest }
     * 
     */
    public GetReservationsListRequest createGetReservationsListRequest() {
        return new GetReservationsListRequest();
    }

    /**
     * Create an instance of {@link GetReservationMessagesResponse }
     * 
     */
    public GetReservationMessagesResponse createGetReservationMessagesResponse() {
        return new GetReservationMessagesResponse();
    }

    /**
     * Create an instance of {@link DeclineReservationResponse }
     * 
     */
    public DeclineReservationResponse createDeclineReservationResponse() {
        return new DeclineReservationResponse();
    }

}
